// Hospital name translations (English -> Arabic)
// Auto-generated for all hospitals in Hospitals_Greater_Cairo_Region.csv
const HOSPITAL_NAMES_AR = {
  "Abbassia Chest Hospital": "مستشفى الصدر بالعباسية",
  "Abdel Kader Fahmy Hospital": "مستشفى عبد القادر فهمي",
  "Accidents & Trauma Hospital": "مستشفى الحوادث الإصابات",
  "Adam International Hospital (IVF&ICSI)": "مستشفى آدم الدولي",
  "Agial Hospital": "مستشفى أجيال",
  "Agial Hospital (Assisted Reproduction), Gynecologic Endoscopy, Obstetrics & Gynecology, NICU)": "مستشفى أجيال",
  "Agouza Diagnostic Center": "مركز التشخيص العجوزة",
  "Agouza General Hospital": "المستشفى العام العجوزة",
  "Agouza Medical Center": "المركز الطبي العجوزة",
  "Agouza Private Clinic": "العيادة الخاصة العجوزة",
  "Agouza Specialized Hospital": "المستشفى التخصصي العجوزة",
  "Agouza Surgical Hospital": "مستشفى الجيزة الجراحية",
  "Agouza Teaching Hospital": "المستشفى التعليمي العجوزة",
  "Ahmed Maher Teaching Hospital": "المستشفى التعليمي أحمد ماهر",
  "Ain Shams Hospital": "مستشفى عين شمس",
  "Ain Shams Specialized Hospital, Abbasia": "مستشفى عين شمس التخصصي",
  "Ain Shams University Hospital (El Demerdash)": "مستشفى عين شمس الجامعي",
  "Al Fatah Specialized Hospital": "المستشفى التخصصي ال الفتح",
  "Al Forkan Specialized Hospital": "المستشفى التخصصي ال الفرقان",
  "Al Fredaws Specialized Hospital": "المستشفى التخصصي ال الفردوس",
  "Al Goumhoria Hospital": "مستشفى الجمهورية",
  "Al Haram Hospital": "مستشفى الحرم",
  "Al Haramain Specialized Hospital": "مستشفى الحرمين التخصصية",
  "Al Helal Al Ahmar Hospital": "مستشفى الهلال الأحمر",
  "Al Mansoura Hospital": "مستشفى المنصورة",
  "Al Montazah Specialized Hospital": "المستشفى التخصصي ال المنتزه",
  "Al Nasr Hospital": "مستشفى النصر",
  "Al Nil Hospital": "مستشفى ال النيل",
  "Al Noor Hospital": "مستشفى ال النور",
  "Al Obour Specialized Hospital": "المستشفى التخصصي ال العبور",
  "Al Salam Hospital": "مستشفى السلام",
  "Al Salama Al jadeeda Hospital": "مستشفى السلام الجديدة",
  "Al Taisseir Specialized Hospital": "مستشفى التيسير التخصصية",
  "Al-Azhar University Hospital": "المستشفى الجامعي ال الأزهر",
  "Aldar Hospital, Zagazig": "مستشفى الدار بالزقازيق",
  "Alexandria Main University hospital (El Meery, Koleyet El Teb)": "مستشفى الإسكندرية الرئيسي الجامعي",
  "Alexandria University Hospitals:": "مستشفيات جامعة الإسكندرية",
  "Alkawther Hospital": "مستشفى الكوثر",
  "Alzahra Hospital": "مستشفى الزهراء",
  "Alzakazik International Hospital": "مستشفى الزقازيق الدولية",
  "Amoun Hospital": "مستشفى آمون",
  "Anwar Al Haramain Hospital": "مستشفى أنوار الحرمين",
  "As Salam International Hospital of Alameda Health Care": "مستشفى السلام الدولي",
  "As Salam International Hospital, Corniche El Nile, Maadi": "مستشفى As السلام الدولي مستشفى الكورنيش ال النيل المعادي",
  "Asyout University Hospital": "مستشفى أسيوط الجامعي",
  "Bab El-Sheria Diagnostic Center": "مركز التشخيص باب ال الشرعية",
  "Bab El-Sheria Hospital": "مستشفى باب الشرعية",
  "Bab El-Sheria Specialized Hospital": "المستشفى التخصصي باب الشرعية",
  "Bab El-Sheria Teaching Hospital": "المستشفى التعليمي باب الشرعية",
  "Badrawy Hospital": "مستشفى بدراوي",
  "Behman Hospital, Maddi": "مستشفى بهمان",
  "Benha Diagnostic Center": "مركز التشخيص بنها",
  "Benha Emergency Medical Center": "مركز الطوارئ الطبي بنها",
  "Benha General Hospital": "المستشفى العام بنها",
  "Benha Medical Center": "المركز الطبي بنها",
  "Benha Private Clinic": "العيادة الخاصة بنها",
  "Benha Specialized Hospital": "المستشفى التخصصي بنها",
  "Benha Surgical Hospital": "المستشفى الجراحي بنها",
  "Benha Teaching Hospital": "المستشفى التعليمي بنها",
  "Borg El Arab University Hospital": "مستشفى برج العرب الجامعي",
  "Boulaq Al": "مستشفى بولاق ال",
  "Cairo University Hospital": "المستشفى الجامعي القاهرة",
  "Chest Diseases Hospital": "مستشفى أمراض الصدر",
  "Chest Hospital (Egypt)": "مستشفى الصدرية",
  "Cleopatra Hospital, Heliopolis": "مستشفى كليوباترا",
  "Coptic Hospital": "مستشفى الأقباط",
  "Dar Al Baraka Hospital": "مستشفى دار ال البركة",
  "Dar Al Fouad Hospital": "مستشفى دار الفؤاد",
  "Dar Al Fouad Hospital (Heart clinic and surgery)": "مستشفى دار الفؤاد (قلب وجراحة)",
  "Dar Al Noor Hospital": "مستشفى دار النور",
  "Dar el Hekma Hospital, Nasr City": "مستشفى دار الحكمة",
  "Dar el Oyoun Eye Hospital": "مستشفى العيون دار العيون",
  "Dar el Oyoun Hospital": "مستشفى دار العيون",
  "Dar el Salam General Hospital": "مستشفى دار السلام العام",
  "Dar El Shefa Hospital": "مستشفى دار الشفاء",
  "Dar ELAraby Maternity Hospital": "مستشفى دار العربي للولادة",
  "Demerdash Hospital": "مستشفى الدمرداش",
  "Dokki General Hospital": "المستشفى العام الدقي",
  "Dokki Medical Center": "المركز الطبي الدقي",
  "Dokki Private Clinic": "العيادة الخاصة الدقي",
  "Dokki Specialized Hospital": "المستشفى التخصصي الدقي",
  "Dokki Surgical Hospital": "المستشفى الجراحي الدقي",
  "Dokki Teaching Hospital": "المستشفى التعليمي الدقي",
  "Downtown Diagnostic Center": "مركز التشخيص وسط البلد",
  "Downtown Emergency Medical Center": "مركز الطوارئ الطبي وسط البلد",
  "Downtown General Hospital": "المستشفى العام وسط البلد",
  "Downtown Medical Center": "المركز الطبي وسط البلد",
  "Downtown Private Clinic": "العيادة الخاصة وسط البلد",
  "Downtown Teaching Hospital": "المستشفى التعليمي وسط البلد",
  "Dr. Hamdy El Sayed Hospital": "مستشفى دكتور حمدي السيد",
  "Dr. Hassab Hospital": "مستشفى الدكتور حسب",
  "Ebtihag Shafik Hospital": "مستشفى ابتهاج شفيق",
  "Economic Treatment – Iktessady": "مستشفى الاقتصادي العلاج الاقتصادي",
  "El Borg Hospital": "مستشفى البرج",
  "El Delta Abdel Latif Hospital": "مستشفى الدلتا عبد اللطيف",
  "El Fayrouz Hospital": "مستشفى الفيروز",
  "El Galaa Hospital": "مستشفى الجلاء",
  "El Ganzouri Specialized Hospital": "مستشفى الجنزوري التخصصي",
  "El Gomhoureyaa Hospital": "مستشفى الجمهورية",
  "El Hadara (Queen Nariman Hospital) for Orthopaedics and Neuropsychiatry": "مستشفى الحضرة للعظام والطب النفسي",
  "El Kablat Hospital": "مستشفى القبلات",
  "El Kateb": "مستشفى الكاتب",
  "El Kenayate District Hospital": "مستشفى الكنايات المركزية",
  "El Ma'moora Psychiatry Hospital": "مستشفى الممورة للطب النفسي",
  "El Mabarah": "مستشفى المبرة",
  "El Madina Hospital": "مستشفى المدينة",
  "El Maleka Nazly Paediatric Hospital": "مستشفى الملكة نازلي لطب الأطفال",
  "El Merghany Hospital": "مستشفى المرغني",
  "El Mobarra Maadi Hospital": "مستشفى المبرة المعادي",
  "El Monera General Hospital": "مستشفى المنيرة العام",
  "El Nada Maternity Hospital": "مستشفى الندى للولادة",
  "El Nozha International Hospital, Heliopolis": "مستشفى النزهة الدولي",
  "El Safa Hospital": "مستشفى الصفا",
  "El Salam Hospital El Haram": "مستشفى السلام الهرم",
  "El Seguini (El Sammak Hospital)": "مستشفى السيجيني",
  "El Shorouk Diagnostic Center": "مركز التشخيص الشروق",
  "El Shorouk Emergency Medical Center": "مركز الطوارئ الطبي الشروق",
  "El Shorouk General Hospital": "المستشفى العام الشروق",
  "El Shorouk Medical Center": "المركز الطبي الشروق",
  "El Shorouk Private Clinic": "العيادة الخاصة الشروق",
  "El Shorouk Specialized Hospital": "المستشفى التخصصي الشروق",
  "El Shorouk Surgical Hospital": "المستشفى الجراحي الشروق",
  "El Shorouk Teaching Hospital": "المستشفى التعليمي الشروق",
  "El Shoruk Hospital": "مستشفى الشروق",
  "El Tawfiaiia Hospital": "مستشفى التوفيقية",
  "Emergency – Istekbal": "مستشفى الطوارئ الاستقبال",
  "Faculty of Medicine Giza Hospital": "مستشفى كلية الطب بالجيزة",
  "Farook Ophthalmology Hospital": "مستشفى فاروق لطب العيون",
  "Fatih MediPlex Hospital": "مستشفى فاتح ميديبلكس",
  "Fayoum General Hospital": "المستشفى العام الفيوم",
  "Fever Hospital": "مستشفى الحمى",
  "Fifth Settlement Emergency Medical Center": "مركز الطوارئ الطبي الخامس التجمع",
  "Fifth Settlement General Hospital": "المستشفى العام الخامس التجمع",
  "Fifth Settlement Medical Center": "المركز الطبي الخامس التجمع",
  "Fifth Settlement Private Clinic": "العيادة الخاصة الخامس التجمع",
  "Gamal Abdel Nasser Hospital": "مستشفى جمال عبد الناصر",
  "Garden City Diagnostic Center": "مركز التشخيص جاردن مدينة",
  "Garden City Emergency Medical Center": "مركز الطوارئ الطبي جاردن مدينة",
  "Garden City General Hospital": "المستشفى العام جاردن مدينة",
  "Garden City Hospital": "مستشفى جاردن سيتي",
  "Garden City Medical Center": "المركز الطبي جاردن مدينة",
  "Garden City Private Clinic": "العيادة الخاصة جاردن مدينة",
  "Garden City Surgical Hospital": "المستشفى الجراحي جاردن مدينة",
  "Garden City Teaching Hospital": "المستشفى التعليمي جاردن مدينة",
  "General Medicine Hospital": "مستشفى العام الطب",
  "German Hospital": "المستشفى الألماني",
  "Gezira Diagnostic Center": "مركز التشخيص الجزيرة",
  "Gezira Emergency Medical Center": "مركز الطوارئ الطبي الجزيرة",
  "Gezira General Hospital": "المستشفى العام الجزيرة",
  "Gezira Medical Center": "المركز الطبي الجزيرة",
  "Gezira Private Clinic": "العيادة الخاصة الجزيرة",
  "Gezira Specialized Hospital": "المستشفى التخصصي الجزيرة",
  "Gezira Surgical Hospital": "المستشفى الجراحي الجزيرة",
  "Giza Diagnostic Center": "مركز التشخيص الجيزة",
  "Giza Emergency Medical Center": "مركز الطوارئ الطبي الجيزة",
  "Giza Private Clinic": "العيادة الخاصة الجيزة",
  "Giza Specialized Hospital": "المستشفى التخصصي الجيزة",
  "Gohar Hospital & Women's Health Clinic": "مستشفى جوهر",
  "Greek Hospital Cairo": "المستشفى اليوناني",
  "Hassab Hospital": "مستشفى حسب",
  "Hassabo International Hospital": "مستشفى حسبو الدولي",
  "Helal Hospital": "مستشفى هلال",
  "Heliopolis Diagnostic Center": "مركز التشخيص مصر الجديدة",
  "Heliopolis General Hospital": "مستشفى هليوبليس العام",
  "Heliopolis Medical Center": "المركز الطبي مصر الجديدة",
  "Heliopolis Private Clinic": "العيادة الخاصة مصر الجديدة",
  "Heliopolis Specialized Hospital": "المستشفى التخصصي مصر الجديدة",
  "Heliopolis Surgical Hospital": "المستشفى الجراحي مصر الجديدة",
  "Heliopolis Teaching Hospital": "المستشفى التعليمي مصر الجديدة",
  "Helwan Medical Center": "المركز الطبي حلوان",
  "Helwan Private Clinic": "العيادة الخاصة حلوان",
  "Helwan Specialized Hospital": "المستشفى التخصصي حلوان",
  "Helwan Surgical Hospital": "المستشفى الجراحي حلوان",
  "Helwan Teaching Hospital": "المستشفى التعليمي حلوان",
  "Hemida Medical Center Hospital": "مستشفى حميدة الطبي مركز",
  "Hussein University Hospital": "مستشفى الحسين الجامعي",
  "Ibn Sina Hospital (Egypt), Dokki": "مستشفى ابن سينا",
  "International Eye Hospital": "مستشفى العيون الدولي",
  "Italian Hospital Cairo": "المستشفى الإيطالي",
  "Kasr Al Ainy Hospital": "مستشفى قصر العيني",
  "Kasr El Nile Diagnostic Center": "مركز التشخيص قصر النيل",
  "Kasr El Nile General Hospital": "المستشفى العام قصر النيل",
  "Kasr El Nile Medical Center": "المركز الطبي قصر النيل",
  "Kasr El Nile Specialized Hospital": "المستشفى التخصصي قصر النيل",
  "Kasr El Nile Teaching Hospital": "المستشفى التعليمي قصر النيل",
  "Kasralainy Hospital": "مستشفى قصر العيني",
  "Khanka Diagnostic Center": "مركز التشخيص الخانكة",
  "Khanka Emergency Medical Center": "مركز الطوارئ الطبي الخانكة",
  "Khanka Hospital": "مستشفى الخانكة",
  "Khanka Medical Center": "المركز الطبي الخانكة",
  "Khanka Private Clinic": "العيادة الخاصة الخانكة",
  "Khanka Specialized Hospital": "المستشفى التخصصي الخانكة",
  "Khanka Surgical Hospital": "المستشفى الجراحي الخانكة",
  "Khanka Teaching Hospital": "المستشفى التعليمي الخانكة",
  "Khater Specialized Hospital": "المستشفى التخصصي خاطر",
  "Maadi Diagnostic Center": "مركز التشخيص المعادي",
  "Maadi Emergency Medical Center": "مركز الطوارئ الطبي المعادي",
  "Maadi General Hospital": "المستشفى العام المعادي",
  "Maadi Hospital": "مستشفى المعادي",
  "Maadi Private Clinic": "العيادة الخاصة المعادي",
  "Maadi Specialized Hospital": "المستشفى التخصصي المعادي",
  "Maadi Surgical Hospital": "المستشفى الجراحي المعادي",
  "Maadi Teaching Hospital": "المستشفى التعليمي المعادي",
  "Maghrabi Eye Hospital & Centers": "مراكز و مسشفي المغربي للعيون",
  "Mahalla General Hospital": "المستشفى العام المحلة",
  "Mahalla Hospital": "مستشفى المحلة",
  "Mahalla Specialized Hospital": "المستشفى التخصصي المحلة",
  "Mahalla Surgical Hospital": "المستشفى الجراحي المحلة",
  "Makka Al Mokarrama Hospital": "مستشفى مكة المكرمة",
  "Manial University Hospital": "المستشفى الجامعي المنيل",
  "Mansoura University Hospitals": "مستشفيات جامعة المنصورة",
  "Maternity Hospital Cairo": "مستشفى الولادة بالقاهرة",
  "Military Hospital": "المستشفى العسكري",
  "Misr El Amal Hospital": "مستشفى مصر الأمل",
  "Misr International Hospital": "مستشفى مصر الدولي",
  "Mohandessin Diagnostic Center": "مركز التشخيص المهندسين",
  "Mohandessin Emergency Medical Center": "مركز الطوارئ الطبي المهندسين",
  "Mohandessin Medical Center": "مركز المهندسين الطبي",
  "Mohandessin Private Clinic": "العيادة الخاصة المهندسين",
  "Mohandessin Surgical Hospital": "المستشفى الجراحي المهندسين",
  "Mohandessin Teaching Hospital": "المستشفى التعليمي المهندسين",
  "Mostafa Kamel Military Hospital": "مستشفى مصطفى كامل العسكري",
  "Mubarak Hospital": "مستشفى مبارك",
  "Nasr City Emergency Medical Center": "مركز الطوارئ الطبي نصر مدينة",
  "Nasr City General Hospital": "المستشفى العام نصر مدينة",
  "Nasr City Medical Center": "المركز الطبي نصر مدينة",
  "Nasr City Private Clinic": "العيادة الخاصة نصر مدينة",
  "Nasr City Specialized Hospital": "المستشفى التخصصي نصر مدينة",
  "Nasr City Surgical Hospital": "المستشفى الجراحي نصر مدينة",
  "Nasr City Teaching Hospital": "المستشفى التعليمي نصر مدينة",
  "Nasser General Hospital": "مستشفى ناصر العام",
  "National Heart Institute": "مستشفى الوطني للقلب",
  "National Liver Institute": "مستشفى الوطني للكبد",
  "New Cairo Diagnostic Center": "مركز التشخيص نيو القاهرة",
  "New Cairo Emergency Medical Center": "مركز الطوارئ الطبي نيو القاهرة",
  "New Cairo General Hospital": "المستشفى العام نيو القاهرة",
  "New Cairo Hospital": "مستشفى القاهرة الجديدة",
  "New Cairo Medical Center": "المركز الطبي نيو القاهرة",
  "New Cairo Private Clinic": "العيادة الخاصة نيو القاهرة",
  "New Cairo Specialized Hospital": "المستشفى التخصصي نيو القاهرة",
  "New Cairo Surgical Hospital": "المستشفى الجراحي نيو القاهرة",
  "New Giza Diagnostic Center": "مركز التشخيص نيو الجيزة",
  "New Giza Emergency Medical Center": "مركز الطوارئ الطبي نيو الجيزة",
  "New Giza Hospital": "مستشفى نيو الجيزة",
  "New Giza Medical Center": "المركز الطبي نيو الجيزة",
  "New Giza Private Clinic": "العيادة الخاصة نيو الجيزة",
  "New Giza Specialized Hospital": "المستشفى التخصصي نيو الجيزة",
  "New Giza Surgical Hospital": "المستشفى الجراحي نيو الجيزة",
  "New Giza Teaching Hospital": "مستشفى الجيزة التعليمي الجديد",
  "New Kasr El Aini Hospital": "مستشفى قصر العيني الجديد",
  "New Surgery Hospital": "مستشفى نيو الجراحة",
  "Nile Badrawi Hospital": "مستشفى النيل بدراوي",
  "Nour Al Eslam Hospital": "مستشفى نور الإسلام",
  "October 6 University (O6U) Hospital": "مستشفى أكتوبر 6 الجامعي",
  "October 6th Diagnostic Center": "مركز التشخيص أكتوبر السادس",
  "October 6th Emergency Medical Center": "مركز الطوارئ الطبي أكتوبر السادس",
  "October 6th Medical Center": "المركز الطبي أكتوبر السادس",
  "October 6th Private Clinic": "العيادة الخاصة أكتوبر السادس",
  "October 6th Surgical Hospital": "المستشفى الجراحي أكتوبر السادس",
  "October 6th Teaching Hospital": "المستشفى التعليمي أكتوبر السادس",
  "Oncology Hospital": "مستشفى الأورام",
  "Ophthalmic Hospital": "مستشفى العيون",
  "Palestine Hospital (Long Term Care)": "مستشفى فلسطين (الرعاية الطويلة المدى)",
  "Port Ghalib Hospital": "مستشفى بورت غالب",
  "Qaiyub Medical Center": "مركز قايوب الطبي",
  "Qalyub Diagnostic Center": "مركز التشخيص قليوب",
  "Qalyub Emergency Medical Center": "مركز الطوارئ الطبي قليوب",
  "Qalyub General Hospital": "المستشفى العام قليوب",
  "Qalyub Medical Center": "المركز الطبي قليوب",
  "Qalyub Private Clinic": "العيادة الخاصة قليوب",
  "Qalyub Specialized": "مستشفى قليوب التخصصي",
  "Qalyub Specialized Hospital": "المستشفى التخصصي قليوب",
  "Qalyub Teaching Hospital": "المستشفى التعليمي قليوب",
  "Qalyubia General Hospital": "المستشفى العام القليوبية",
  "Qalyubia Medical Center": "المركز الطبي القليوبية",
  "Red Sea Hospital": "مستشفى البحر الأحمر",
  "Rehab Emergency Medical Center": "مركز الطوارئ الطبي الرحاب",
  "Rehab General Hospital": "المستشفى العام الرحاب",
  "Rehab Hospital": "مستشفى الرحاب",
  "Rehab Private Clinic": "العيادة الخاصة الرحاب",
  "Rehab Specialized Hospital": "المستشفى التخصصي الرحاب",
  "Rehab Surgical Hospital": "المستشفى الجراحي الرحاب",
  "Rehab Teaching Hospital": "المستشفى التعليمي الرحاب",
  "Rowad Eye Hospital": "مستشفى العيون الرواد",
  "Roxy Hospital": "مستشفى روكسي",
  "Saad Soliman Hospital": "مستشفى سعد سليمان",
  "Saudi German Hospital (SGH)": "المستشفى السعودي الألماني",
  "Saudi German Hospital SGH Cairo (150 Beds General Hospital)": "المستشفى السعودي الألماني",
  "Sharm International Hospital": "مستشفى شرم الدولية",
  "Sheikh Zayed Hospital": "مستشفى الشيخ زايد",
  "Sheikh Zayed Medical Center": "المركز الطبي الشيخ زايد",
  "Sheikh Zayed specialized Hospital": "مستشفى الشيخ زايد التخصصي",
  "Shubra General Hospital": "المستشفى العام شبرا",
  "Shubra Hospital": "مستشفى شبرا",
  "Shubra Medical Center": "المركز الطبي شبرا",
  "Shubra Private Clinic": "العيادة الخاصة شبرا",
  "Shubra Specialized Hospital": "المستشفى التخصصي شبرا",
  "Shubra Teaching Hospital": "المستشفى التعليمي شبرا",
  "Siklam Hospital": "مستشفى سكلام",
  "Socialized Surgery": "مستشفى التأميني الجراحة",
  "South Sinai Hospital": "مستشفى جنوب سيناء",
  "Specialized Medicine Hospital": "مستشفى التخصصي الطب",
  "Tanta General Hospital": "المستشفى العام طنطا",
  "The Egyptian Hospital": "المستشفى المصري",
  "Toukh Diagnostic Center": "مركز التشخيص طوخ",
  "Toukh Emergency Medical Center": "مركز الطوارئ الطبي طوخ",
  "Toukh Hospital": "مستشفى طوخ",
  "Toukh Medical Center": "المركز الطبي طوخ",
  "Toukh Specialized Hospital": "المستشفى التخصصي طوخ",
  "Toukh Teaching Hospital": "المستشفى التعليمي طوخ",
  "Tumor & Oncology Hospital": "مستشفى الأورام الأورام",
  "Victoria Hospital": "مستشفى فيكتوريا",
  "Victorya Hospital": "مستشفى فيكتوريا",
  "Waly For Surgery Hospital": "مستشفى والي للجراحة",
  "Watany Eye Hospitals": "مستشفيات وطني للعيون",
  "Zahraa University Hospital": "مستشفى الزهراء الجامعي",
  "Zamalek Diagnostic Center": "مركز التشخيص الزمالك",
  "Zamalek Emergency Medical Center": "مركز الطوارئ الطبي الزمالك",
  "Zamalek Hospital": "مستشفى الزمالك",
  "Zamalek Private Clinic": "العيادة الخاصة الزمالك",
  "Zamalek Specialized Hospital": "المستشفى التخصصي الزمالك",
  "Zamalek Surgical Hospital": "المستشفى الجراحي الزمالك",
  "Zamalek Teaching Hospital": "المستشفى التعليمي الزمالك",
  "Zohairy Hospital": "مستشفى الزهيري",
};

function normalizeArabicHospitalName(name) {
  return name.replace(/\sال\s+ال\s+/g, ' ال').replace(/\s+/g, ' ').trim();
}

function getHospitalNameInLanguage(englishName, language) {
  if (language === 'ar') {
    const translated = HOSPITAL_NAMES_AR[englishName];
    return translated ? normalizeArabicHospitalName(translated) : englishName;
  }
  return englishName;
}
