// Hospital name translations (English -> Arabic)
// Comprehensive translation of all hospitals from CSV data
const HOSPITAL_NAMES_AR = {
  // Existing hospitals
  'Abdel Kader Fahmy Hospital': 'مستشفى عبد القادر فهمي',
  'Adam International Hospital (IVF&ICSI)': 'مستشفى آدم الدولي',
  'Ain Shams Specialized Hospital, Abbasia': 'مستشفى عين شمس التخصصي',
  'Ain Shams University Hospital (El Demerdash)': 'مستشفى عين شمس الجامعي',
  'Al Salam Hospital': 'مستشفى السلام',
  'Alzahra Hospital': 'مستشفى الزهراء',
  'As Salam International Hospital of Alameda Health Care': 'مستشفى السلام الدولي',
  'Amoun Hospital': 'مستشفى آمون',
  'Asyout University Hospital': 'مستشفى أسيوط الجامعي',
  'Behman Hospital, Maddi': 'مستشفى بهمان',
  'Cleopatra Hospital, Heliopolis': 'مستشفى كليوباترا',
  'Coptic Hospital': 'مستشفى الأقباط',
  'Dar Al Fouad Hospital': 'مستشفى دار الفؤاد',
  'Dar el Hekma Hospital, Nasr City': 'مستشفى دار الحكمة',
  'Dar el Salam General Hospital': 'مستشفى دار السلام العام',
  'Dar el Oyoun Hospital': 'مستشفى دار العيون',
  'Dar El Shefa Hospital': 'مستشفى دار الشفاء',
  'Demerdash Hospital': 'مستشفى الدمرداش',
  'El Borg Hospital': 'مستشفى البرج',
  'El Fayrouz Hospital': 'مستشفى الفيروز',
  'El Ganzouri Specialized Hospital': 'مستشفى الجنزوري التخصصي',
  'El Galaa Hospital': 'مستشفى الجلاء',
  'El Gomhoureyaa Hospital': 'مستشفى الجمهورية',
  'El Kablat Hospital': 'مستشفى القبلات',
  'El Kateb': 'مستشفى الكاتب',
  'El Madina Hospital': 'مستشفى المدينة',
  'El Merghany Hospital': 'مستشفى المرغني',
  'El Mobarra Maadi Hospital': 'مستشفى المبرة المعادي',
  'El Monera General Hospital': 'مستشفى المنيرة العام',
  'El Nada Maternity Hospital': 'مستشفى الندى للولادة',
  'El Nozha International Hospital, Heliopolis': 'مستشفى النزهة الدولي',
  'El Salam Hospital El Haram': 'مستشفى السلام الهرم',
  'El Safa Hospital': 'مستشفى الصفا',
  'El Shoruk Hospital': 'مستشفى الشروق',
  'El Tawfiaiia Hospital': 'مستشفى التوفيقية',
  'Ebtihag Shafik Hospital': 'مستشفى ابتهاج شفيق',
  'Gohar Hospital & Women\'s Health Clinic': 'مستشفى جوهر',
  'Garden City Hospital': 'مستشفى جاردن سيتي',
  'Hassabo International Hospital': 'مستشفى حسبو الدولي',
  'Hussein University Hospital': 'مستشفى الحسين الجامعي',
  'Ibn Sina Hospital (Egypt), Dokki': 'مستشفى ابن سينا',
  'Italian Hospital Cairo': 'المستشفى الإيطالي',
  'Greek Hospital Cairo': 'المستشفى اليوناني',
  'Kasralainy Hospital': 'مستشفى قصر العيني',
  'Misr El Amal Hospital': 'مستشفى مصر الأمل',
  'Nasser General Hospital': 'مستشفى ناصر العام',
  'New Kasr El Aini Hospital': 'مستشفى قصر العيني الجديد',
  'New Cairo Hospital': 'مستشفى القاهرة الجديدة',
  'Nile Badrawi Hospital': 'مستشفى النيل بدراوي',
  'October 6 University (O6U) Hospital': 'مستشفى أكتوبر 6 الجامعي',
  'Roxy Hospital': 'مستشفى روكسي',
  'Saudi German Hospital SGH Cairo (150 Beds General Hospital)': 'المستشفى السعودي الألماني',
  'Sheikh Zayed specialized Hospital': 'مستشفى الشيخ زايد التخصصي',
  'Watany Eye Hospitals': 'مستشفيات وطني للعيون',
  'Zahraa University Hospital': 'مستشفى الزهراء الجامعي',
  'Zohairy Hospital': 'مستشفى الزهيري',
  'Agial Hospital (Assisted Reproduction), Gynecologic Endoscopy, Obstetrics & Gynecology, NICU)': 'مستشفى أجيال',
  'Alexandria University Hospitals:': 'مستشفيات جامعة الإسكندرية',
  'Borg El Arab University Hospital': 'مستشفى برج العرب الجامعي',
  'Alexandria Main University hospital (El Meery, Koleyet El Teb)': 'مستشفى الإسكندرية الرئيسي الجامعي',
  'El Hadara (Queen Nariman Hospital) for Orthopaedics and Neuropsychiatry': 'مستشفى الحضرة للعظام والطب النفسي',
  'Al Salama Al jadeeda Hospital': 'مستشفى السلام الجديدة',
  'Agial Hospital': 'مستشفى أجيال',
  'Badrawy Hospital': 'مستشفى بدراوي',
  'Dar ELAraby Maternity Hospital': 'مستشفى دار العربي للولادة',
  'Dr. Hassab Hospital': 'مستشفى الدكتور حسب',
  'Al Helal Al Ahmar Hospital': 'مستشفى الهلال الأحمر',
  'El Ma\'moora Psychiatry Hospital': 'مستشفى الممورة للطب النفسي',
  'El Maleka Nazly Paediatric Hospital': 'مستشفى الملكة نازلي لطب الأطفال',
  'El Seguini (El Sammak Hospital)': 'مستشفى السيجيني',
  'Farook Ophthalmology Hospital': 'مستشفى فاروق لطب العيون',
  'German Hospital': 'المستشفى الألماني',
  'Gamal Abdel Nasser Hospital': 'مستشفى جمال عبد الناصر',
  'Saudi German Hospital (SGH)': 'المستشفى السعودي الألماني',
  'Victoria Hospital': 'مستشفى فيكتوريا',
  'Hassab Hospital': 'مستشفى حسب',
  'Victorya Hospital': 'مستشفى فيكتوريا',
  'Siklam Hospital': 'مستشفى سكلام',
  'Alkawther Hospital': 'مستشفى الكوثر',
  'The Egyptian Hospital': 'المستشفى المصري',
  'Red Sea Hospital': 'مستشفى البحر الأحمر',
  'Port Ghalib Hospital': 'مستشفى بورت غالب',
  'Mansoura University Hospitals': 'مستشفيات جامعة المنصورة',
  'Sharm International Hospital': 'مستشفى شرم الدولية',
  'El Kenayate District Hospital': 'مستشفى الكنايات المركزية',
  'El Mabarah': 'مستشفى المبرة',
  'Chest Hospital (Egypt)': 'مستشفى الصدرية',
  'Fever Hospital': 'مستشفى الحمى',
  'Ophthalmic Hospital': 'مستشفى العيون',
  'Fatih MediPlex Hospital': 'مستشفى فاتح ميديبلكس',
  'Al Haramain Specialized Hospital': 'مستشفى الحرمين التخصصية',
  'Anwar Al Haramain Hospital': 'مستشفى أنوار الحرمين',
  'Al Taisseir Specialized Hospital': 'مستشفى التيسير التخصصية',
  'Al Nasr Hospital': 'مستشفى النصر',
  'Al Goumhoria Hospital': 'مستشفى الجمهورية',
  'Aldar Hospital, Zagazig': 'مستشفى الدار بالزقازيق',
  'El Delta Abdel Latif Hospital': 'مستشفى الدلتا عبد اللطيف',
  'Alzakazik International Hospital': 'مستشفى الزقازيق الدولية',
  'Mohandessin Medical Center': 'مركز المهندسين الطبي',
  'Faculty of Medicine Giza Hospital': 'مستشفى كلية الطب بالجيزة',
  'New Giza Teaching Hospital': 'مستشفى الجيزة التعليمي الجديد',
  'Military Hospital': 'المستشفى العسكري',
  'Agouza Surgical Hospital': 'مستشفى الجيزة الجراحية',
  'Heliopolis General Hospital': 'مستشفى هليوبليس العام',
  'Qaiyub Medical Center': 'مركز قايوب الطبي'
};

function getHospitalNameInLanguage(englishName, language) {
  if (language === 'ar') {
    return HOSPITAL_NAMES_AR[englishName] || englishName;
  }
  return englishName;
}
